### ISSUE TITLE
Problems with inspect4py

### ISSUE THREAD

**Issue by esgg** [oeg-upm/soca#61]
During the execution of the command extract, I get the following messages (among others):

Extracting metadata from https://github.com/oeg-upm/pcake                                                                                                               
ERROR: Could not extract metadata from https://github.com/oeg-upm/pcake
Extracting metadata from https://github.com/oeg-upm/delta-ontology                                                                                                      
Extracting metadata from https://github.com/oeg-upm/ainn-request                                                                                                        
ERROR: Could not run inspect4py for https://github.com/oeg-upm/ainn-request: Error in sowftware_type software_invocation
Extracting metadata from https://github.com/oeg-upm/ainn-website                                                                                                        
Extracting metadata from https://github.com/oeg-upm/PPool                                                                                                               
ERROR: Could not run inspect4py for https://github.com/oeg-upm/PPool: Error in sowftware_type software_invocation

-----------------------

The version of inspect4py is 0.0.1

I have executed the command inpect4py directly with one of the repositories and it works. It generates the JSON file with the results.

**Comment by dgarijo** [comment]
@esgg,
I am confused: We should not run inspect4py with  repos like https://github.com/oeg-upm/delta-ontology because it's not python

However, it should work for https://github.com/oeg-upm/pcake because it's Python 3.9. Is this the repo you executed above?

I guess my confusion here is: Is the problem that soca cannot run inspect4py; or that inspect4py produces errors?

**Comment by esgg** [comment]
Yes, soca only runs inspect4py with python repositories.  In the case of https://github.com/oeg-upm/delta-ontology, soca doesn't run inspect4py (that is the reason that no error message appears).

I ran inspect4py with another python repository. 

My feeling is that the problem is from soca side. Something related with the execution of inspect4py, but the message doesn't provide much information.

**Comment by dgarijo** [comment]
Ok, now it's clear to me. It does look like a `soca` error

**Comment by dakixr** [comment]
Sorry my fault, I missed a / in the code :D
