### ISSUE TITLE
Wrong requirements

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/soca#71]
In https://dakixr.github.io/scc/example/KnowledgeCaptureAndDiscoveryANDmintproject/index.html, repo [model-catalog-python-api-client](https://github.com/mintproject/model-catalog-python-api-client), soca shows very long requirements.

However, Somef seems to retrieve this information nicely. Maybe somef 0.8.2 is not being used??

**Comment by dakixr** [comment]
I'm currently using somef 0.8.1. As I thought it was the latest release. Is there a new release?

**Comment by dgarijo** [comment]
No, sorry, I got this one wrong. I was seeing the reduced version of the paragraph. It's a somef problem

**Comment by dgarijo** [comment]
However, soca does not aggregate the installation instructions in this repository
