### ISSUE TITLE
Wrong repository clone url

### ISSUE THREAD

**Issue by esgg** [oeg-upm/soca#83]
In the section "Install from Github", you clone the repo from a different url

**Comment by dgarijo** [comment]
Can you elaborate a bit, please?

**Comment by esgg** [comment]
Sure. In the Installation section, the command  to clone the repo is **git clone https://github.com/dakixr/soca**.  The url should be  https://github.com/oeg-upm/soca.

**Comment by dgarijo** [comment]
Ahhh indeed!
